version: '3.1'

services:
  jenkins:
    build: ./docker/jenkins
    volumes:
      - ./docker/jenkins/jenkins_data:/var/jenkins_home
      - $HOME:/home
      - ./docker/jenkins/downloads:/var/jenkins_home/downloads
    networks:
      - jenkins
    ports:
      - 8080:8080
    environment:
      - DOCKER_HOST=tcp://socat:2375
    secrets:
      - artifactoryPassword

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    networks:
      - jenkins
    ports:
      - 9000:9000

  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-cpp-ce:latest
    networks:
      - jenkins
    ports:
      - 8081:8081

networks:
  jenkins:
    driver: bridge

secrets:
  artifactoryPassword:
    file: ./docker/artifactory/secrets/artifactoryPassword