version: '2'

services:
  jenkins:
    image: jenkinsci/blueocean
    volumes:
      - ./docker/jenkins/jenkins_data:/var/jenkins_home
      - $HOME:/home
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://socat:2375
      - SONARQUBE_HOST=http://sonarqube:9000
    links:
      - socat
      - sonarqube
  #https://medium.com/@mingheng/solving-permission-denied-while-trying-to-connect-to-docker-daemon-socket-from-container-in-mac-os-600c457f1276
  #https://hub.docker.com/r/alpine/socat/
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"
    networks:
      - jenkins

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    networks:
      - jenkins
    ports:
      - 9000:9000

networks:
  jenkins:
    driver: bridge