version: '2'
services:
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local
  springdevops:
    image: slackerwx/spring-devops:spring-devops
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      DATABASESERVER_PORT: "5432"
  #Attention:  Replace the value in the “command” attribute with the value supplied to you from Papertrail
  logspout:
    image: gliderlabs/logspout
    command: syslog://logs4.papertrailapp.com:53892
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
